# <center> Avito Cars data cleaning <center>

In [17]:
import tensorflow

In [67]:
# import libreries 
import pandas as pd
import numpy as np
import seaborn as sn
import matplotlib.pyplot as plt
#import plotly.express as px  
import time
import datetime as dt
pd.set_option("display.max_rows" , 25)

In [7]:
df1 = pd.read_csv("avito_cars_data_0_5000K_LV.csv")
df2 = pd.read_csv("avito_cars_data_5000_10000.csv")
df3 = pd.read_csv("avito_cars_data_10K_20K.csv")
df4 = pd.read_csv("avito_cars_data_20000_25000_LV.csv")
df5 =  pd.read_csv("avito_cars_data_25000_30000K_LV.csv")
df6 =  pd.read_csv("avito_cars_data_35000_40000_LV.csv")
df7 =  pd.read_csv("avito_cars_data_40000_46200K_LV.csv")
df8 = pd.read_csv("avito_cars_data_40000_46200K_LV.csv")
df9 = pd.read_csv("avito_cars_data_46200_50000K_LV.csv")
df10 = pd.read_csv("avito_cars_data_50000_56100_LV.csv")
df11 = pd.read_csv("avito_cars_data_56100_60000_LV.csv")
df12 = pd.read_csv("avito_cars_data_60000_66100.csv")
df13 = pd.read_csv("avito_cars_data_66100_70000_LV.csv")
df14 = pd.read_csv("avito_cars_data_70000_75364K_LV.csv")


data =pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,
                 df10, df11, df12, df13, df14],axis=0)
data.head(5)

,Unnamed: 0,Location,Price,Posting_time,Hors_power,Troust,Energy,Description,Type,Secteur,Nombre de portes,Année-Modèle,État,Kilométrage,Première main,Origine,Marque,Modèle,link
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
data.Type

0        Voitures d'occasion, à vendre
1        Voitures d'occasion, à vendre
2        Voitures d'occasion, à vendre
3        Voitures d'occasion, à vendre
4        Voitures d'occasion, à vendre
                     ...
66725                              NaN
66726    Voitures d'occasion, à vendre
66727    Voitures d'occasion, à vendre
66728                              NaN
66729    Voitures d'occasion, à vendre
Name: Type, Length: 66730, dtype: object

In [15]:
data=data[['Location', 'Price', 'Posting_time', 'Hors_power', 'Troust', 'Energy', 'Nombre de portes', 'Année-Modèle',
       'État', 'Kilométrage', 'Première main', 'Origine', 'Marque', 'Modèle']]
data.head(5)

,Location,Price,Posting_time,Hors_power,Troust,Energy,Nombre de portes,Année-Modèle,État,Kilométrage,Première main,Origine,Marque,Modèle
0,Meknès,274000 DH,"6/20/2024, 3:09:36 PM",6 CV,Automatique,Diesel,5.0,2020,Neuf,110 000 - 119 999,Oui,WW au Maroc,Hyundai,Tucson
1,Tétouan,117000 DH,"6/18/2024, 3:11:58 PM",6 CV,Manuelle,Diesel,5.0,2013,Excellent,130 000 - 139 999,Non,WW au Maroc,Fiat,500L
2,Casablanca,195000 DH,"6/21/2024, 8:47:26 AM",12 CV,Automatique,Diesel,5.0,2012,Excellent,190 000 - 199 999,Oui,WW au Maroc,Porsche,Cayenne
3,Casablanca,159000 DH,"6/21/2024, 10:41:00 AM",12 CV,Automatique,Diesel,5.0,2015,Excellent,140 000 - 149 999,Oui,WW au Maroc,Volkswagen,Touareg
4,Fès,140000 DH,"6/11/2024, 3:08:52 PM",6 CV,Manuelle,Diesel,5.0,2018,Neuf,75 000 - 79 999,Non,WW au Maroc,Renault,megane_4

In [16]:
links = pd.read_csv("avito_car_links_6_2024.csv")["links"].to_list()
#data["link"] = links[:data.shape[0]]

In [17]:
#data.drop(columns = ["Unnamed: 0","link"],inplace =True)
data.dropna(how ="all",inplace =True,)
data.drop_duplicates(inplace =True)
data.index = range(data.shape[0])
data.shape

(66729, 14)

In [21]:
data.dropna(axis = 0, how = "any", ignore_index= True, inplace = True)

In [22]:
marks_models ={}
for marque in data["Marque"].unique():
    unique_models = data[data["Marque"]==marque]["Modèle"].unique()
    marks_models[marque] = unique_models
#marks_models

data.Description = data.Description.replace(np.nan,"pas de description")
n=0
def unique_values(col):
    unique_val = list(data[col].unique())
    unique_val.remove(np.nan)
    unique_val = [word for elem in unique_val for word in elem.split()]
    return unique_val

def get_from_description(col,unique_values):
    extracted_values = []
    for i in range(len(data[col])): 
        desc = data["Description"][i].split()
        if type(data[col][i]) == float:
            if np.isnan(data[col][i]):
                result = [elem for elem in unique_values if elem in desc]
                extracted_values.append(" ".join(result if result else ""))
                #print(i,elem, desc.index(elem))  
        else :
               extracted_values.append("")
    return extracted_values

mark_from_desc = get_from_description("Marque", unique_values("Marque"))
data ["Marque_extrait_de_desc"] = mark_from_desc

new_marque = data["Marque"].replace(np.nan,"") + data["Marque_extrait_de_desc"] 

data["Marque"] = new_marque

In [23]:
data[data.Marque==""]

Empty DataFrame
Columns: [Location, Price, Posting_time, Hors_power, Troust, Energy, Nombre de portes, Année-Modèle, État, Kilométrage, Première main, Origine, Marque, Modèle]
Index: []

In [24]:
def get_model_from_description():
    extracted_models = []
    for i in data.index: 
        desc = data["Description"][i].split()
        if type(data["Modèle"][i]) == float:
            if np.isnan(data["Modèle"][i]):
                marque = data.loc[i]["Marque"]
                unique_models = marks_models[marque]
                result = [elem for elem in unique_models if elem in desc]
                extracted_models.append(" ".join(result if result else ""))
                #print(i,elem, desc.index(elem))  
        else :
               extracted_models.append("")
    return extracted_models

columns=["Location","Price","Posting_time","Hors_power","Troust","Energy",
 "Description","Type","Secteur","Nombre de portes","Année-Modèle",
 "État","Kilométrage","Première main","Origine","Marque","Modèle"]
i = 0
for row in data.index:
    if len(data.loc[row][columns].value_counts()) == 0:
        i += 1
        #print(i,":",row)
        data.drop(index=row, inplace = True)

In [29]:
data["Price"]= data["Price"].str.replace("DH","")
data["Price"]= data["Price"].str.replace(" ","")
data["Price"]= data["Price"].str.replace("Prixàlabaisse","")

data.drop(index = data[data["Price"].isna()].index, inplace = True)

data.drop(index = data[data["Price"]=='Prixnonspécifié'].index, inplace = True)
data["Price"]= data["Price"].str.replace('Prixenhausse',"")
data.shape

(49557, 14)

In [30]:
data["Price"].astype(int)

0        274000
1        117000
2        195000
3        159000
4        140000
          ...
49616    105000
49617    115000
49618     25000
49619     92000
49620    120000
Name: Price, Length: 49557, dtype: int32

In [31]:
data = data.reindex()
data.index=range(data.shape[0])
data.index

RangeIndex(start=0, stop=49557, step=1)

In [32]:
# Posting time
posting_time = list()
for i in range(len(data["Posting_time"])):
    pt = None
    date = str(data["Posting_time"][i])
    if date == "nan":
        pt = np.nan
        posting_time.append(pt)
            
    else : 
        month = int(date.split(",")[0].split("/")[0])
        #print(i, month)
        day = int(date.split(",")[0].split("/")[1])
        year = int(date.split(",")[0].split("/")[2])
        pt = (dt.datetime.now()-dt.datetime(year,month,day)).days
        posting_time.append(pt)#np.round(pt))
    
#max(posting_time)

data["posting_days"]=posting_time
data.head(10)

,Location,Price,Posting_time,Hors_power,Troust,Energy,Nombre de portes,Année-Modèle,État,Kilométrage,Première main,Origine,Marque,Modèle,posting_days
0,Meknès,274000,"6/20/2024, 3:09:36 PM",6 CV,Automatique,Diesel,5.0,2020,Neuf,110 000 - 119 999,Oui,WW au Maroc,Hyundai,Tucson,10
1,Tétouan,117000,"6/18/2024, 3:11:58 PM",6 CV,Manuelle,Diesel,5.0,2013,Excellent,130 000 - 139 999,Non,WW au Maroc,Fiat,500L,12
2,Casablanca,195000,"6/21/2024, 8:47:26 AM",12 CV,Automatique,Diesel,5.0,2012,Excellent,190 000 - 199 999,Oui,WW au Maroc,Porsche,Cayenne,9
3,Casablanca,159000,"6/21/2024, 10:41:00 AM",12 CV,Automatique,Diesel,5.0,2015,Excellent,140 000 - 149 999,Oui,WW au Maroc,Volkswagen,Touareg,9
4,Fès,140000,"6/11/2024, 3:08:52 PM",6 CV,Manuelle,Diesel,5.0,2018,Neuf,75 000 - 79 999,Non,WW au Maroc,Renault,megane_4,19
5,Mohammedia,105000,"6/11/2024, 3:04:31 PM",6 CV,Manuelle,Diesel,5.0,2015,Excellent,200 000 - 249 999,Non,WW au Maroc,Citroen,C4,19
6,Tanger,275000,"6/20/2024, 2:59:35 PM",8 CV,Automatique,Diesel,5.0,2016,Très bon,170 000 - 179 999,Oui,Importée neuve,BMW,Serie 1,10
7,Casablanca,217000,"6/12/2024, 2:59:56 PM",8 CV,Automatique,Diesel,5.0,2017,Excellent,110 000 - 119 999,Non,WW au Maroc,Land Rover,Range Rover Evoque,18
8,Temara,155000,"6/20/2024, 2:59:53 PM",8 CV,Automatique,Diesel,5.0,2018,Neuf,160 000 - 169 999,Non,WW au Maroc,Ford,Fusion,10
9,Tanger,258000,"6/20/2024, 2:59:52 PM",9 CV,Automatique,Diesel,5.0,2018,Excellent,170 000 - 179 999,Oui,WW au Maroc,Hyundai,grand_santa_fe,10

In [33]:
data.iloc[0]#["link"]

Location                           Meknès
Price                              274000
Posting_time        6/20/2024, 3:09:36 PM
Hors_power                           6 CV
Troust                        Automatique
Energy                             Diesel
Nombre de portes                      5.0
Année-Modèle                         2020
État                                 Neuf
Kilométrage             110 000 - 119 999
Première main                         Oui
Origine                       WW au Maroc
Marque                            Hyundai
Modèle                             Tucson
posting_days                           10
Name: 0, dtype: object

In [ ]:
data["Hors_power"]=data["Hors_power"].str.replace("CV","")
data["Hors_power"]=data["Hors_power"].str.replace("Plus de 41 ","41 ")
data["Hors_power"]=data["Hors_power"].str.replace(" ","")
data["Hors_power"] = data["Hors_power"].astype(int)

AttributeError: Can only use .str accessor with string values!

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49557 entries, 0 to 49556
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Location          49557 non-null  object
 1   Price             49557 non-null  object
 2   Posting_time      49557 non-null  object
 3   Hors_power        49557 non-null  int32
 4   Troust            49557 non-null  object
 5   Energy            49557 non-null  object
 6   Nombre de portes  49557 non-null  float64
 7   Année-Modèle      49557 non-null  object
 8   État              49557 non-null  object
 9   Kilométrage       49557 non-null  object
 10  Première main     49557 non-null  object
 11  Origine           49557 non-null  object
 12  Marque            49557 non-null  object
 13  Modèle            49557 non-null  object
 14  posting_days      49557 non-null  int64
dtypes: float64(1), int32(1), int64(1), object(12)
memory usage: 5.5+ MB

In [188]:
data.Troust

0        Automatique
1           Manuelle
2        Automatique
3        Automatique
4           Manuelle
            ...
17123       Manuelle
17124       Manuelle
17125       Manuelle
17126       Manuelle
17127       Manuelle
Name: Troust, Length: 17128, dtype: object

In [306]:
data.Energy.value_counts()

Energy
Diesel        29498
Essence        6888
Hybride         267
Electrique       71
Name: count, dtype: int64

In [36]:

data["Année-Modèle"] = data["Année-Modèle"].str.replace("1980 ou plus ancien","1980")#,inplace = True)
data["Année-Modèle"] = data["Année-Modèle"].astype(int)
data["Année-Modèle"]

0        2020
1        2013
2        2012
3        2015
4        2018
         ...
49552    2016
49553    2010
49554    1994
49555    2009
49556    2012
Name: Année-Modèle, Length: 49557, dtype: int32

In [37]:

car_age =[np.round((dt.datetime.now()-dt.datetime(year,1,1)).days/365, 2) for year in data["Année-Modèle"]]
data["Car_age"] = car_age

data["Car_age"]

0         4.50
1        11.50
2        12.50
3         9.50
4         6.50
         ...
49552     8.50
49553    14.50
49554    30.52
49555    15.50
49556    12.50
Name: Car_age, Length: 49557, dtype: float64

In [38]:
data["Origine"].value_counts()

Origine
WW au Maroc             36079
Dédouanée               10664
Importée neuve           2415
Pas encore dédouanée      399
Name: count, dtype: int64

In [39]:
data["Kilométrage"] = data["Kilométrage"].replace('Plus de 500 000',"500000")
 
average_km = []
for item in data.Kilométrage:
   #print(item)
   mean_km = np.mean([int(i) for i in item.replace(" ","").split("-")])
   #print(mean_km)
   average_km.append(mean_km)
   
data["Moyen_Kilomérage"] = average_km

In [79]:
data.head(5)

,Location,Price,Posting_time,Hors_power,Troust,Energy,Nombre de portes,Année-Modèle,État,Kilométrage,Première main,Origine,Marque,Modèle,posting_days,Car_age,Moyen_Kilomérage
0,Meknès,274000,"6/20/2024, 3:09:36 PM",6,Automatique,Diesel,5.0,2020,Neuf,110 000 - 119 999,1,WW au Maroc,Hyundai,Tucson,10,4.5,114999.5
1,Tétouan,117000,"6/18/2024, 3:11:58 PM",6,Manuelle,Diesel,5.0,2013,Excellent,130 000 - 139 999,0,WW au Maroc,Fiat,500L,12,11.5,134999.5
2,Casablanca,195000,"6/21/2024, 8:47:26 AM",12,Automatique,Diesel,5.0,2012,Excellent,190 000 - 199 999,1,WW au Maroc,Porsche,Cayenne,9,12.5,194999.5
3,Casablanca,159000,"6/21/2024, 10:41:00 AM",12,Automatique,Diesel,5.0,2015,Excellent,140 000 - 149 999,1,WW au Maroc,Volkswagen,Touareg,9,9.5,144999.5
4,Fès,140000,"6/11/2024, 3:08:52 PM",6,Manuelle,Diesel,5.0,2018,Neuf,75 000 - 79 999,0,WW au Maroc,Renault,megane_4,19,6.5,77499.5

In [84]:
data_for_eda = data[['Location', 'Price', 'Posting_time', 'Hors_power', 'Troust', 'Energy',
       'Nombre de portes', 'Année-Modèle','État',
       'Première main', 'Origine', 'Marque', 'Modèle', 'posting_days',
       'Car_age', 'Moyen_Kilomérage']]
data_for_eda.to_csv("avito_cars_data_cleaned.csv")

In [41]:
# replace "Oui" et "Non" par 1 et 0 in "Première main" column.
data["Première main"]=data["Première main"].str.replace("Oui","1").str.replace("Non","0").astype(int)

In [68]:

dummies_data = pd.get_dummies(data,columns=["Troust","Energy","Origine"],prefix="",prefix_sep ="",dtype=int)
dummies_data.loc[0]

Location                               Meknès
Price                                  274000
Posting_time            6/20/2024, 3:09:36 PM
Hors_power                                  6
Nombre de portes                          5.0
Année-Modèle                             2020
État                                     Neuf
Kilométrage                 110 000 - 119 999
Première main                               1
Marque                                Hyundai
Modèle                                 Tucson
posting_days                               10
Car_age                                   4.5
Moyen_Kilomérage                     114999.5
Automatique                                 1
Manuelle                                    0
Diesel                                      1
Electrique                                  0
Essence                                     0
Hybride                                     0
Dédouanée                                   0
Importée neuve                              0
Pas encore dédouanée                        0
WW au Maroc                                 1
Name: 0, dtype: object

In [69]:
dummies_data["État"].value_counts()
car_state_mapping = {
    'Neuf': 10,
    'Excellent': 9,
    'Très bon': 8,
    'Bon': 7,
    'Correct': 6,
    'Pour Pièces': 5,
    'Endommagé': 4
}

dummies_data["État_encodée"] = dummies_data["État"].map(car_state_mapping)

In [73]:
dummies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49557 entries, 0 to 49556
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Location              49557 non-null  object
 1   Price                 49557 non-null  object
 2   Posting_time          49557 non-null  object
 3   Hors_power            49557 non-null  int32
 4   Nombre de portes      49557 non-null  float64
 5   Année-Modèle          49557 non-null  int32
 6   État                  49557 non-null  object
 7   Kilométrage           49557 non-null  object
 8   Première main         49557 non-null  int32
 9   Marque                49557 non-null  object
 10  Modèle                49557 non-null  object
 11  posting_days          49557 non-null  int64
 12  Car_age               49557 non-null  float64
 13  Moyen_Kilomérage      49557 non-null  float64
 14  Automatique           49557 non-null  int32
 15  Manuelle              49557 non-null  int32
 16  Diesel                49557 non-null  int32
 17  Electrique            49557 non-null  int32
 18  Essence               49557 non-null  int32
 19  Hybride               49557 non-null  int32
 20  Dédouanée             49557 non-null  int32
 21  Importée neuve        49557 non-null  int32
 22  Pas encore dédouanée  49557 non-null  int32
 23  WW au Maroc           49557 non-null  int32
 24  État_encodée          49557 non-null  int64
dtypes: float64(3), int32(13), int64(2), object(7)
memory usage: 7.0+ MB